// <auto-generated />
using System;
using CryptoWeb.Shared.Models.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoWeb.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250725004329_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("CryptoWeb.Shared.Models.Entities.FaucetUser", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastClaim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Session")
                        .HasColumnType("TEXT");

                    b.Property<int>("TodayClaim")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalClaim")
                        .HasColumnType("INTEGER");

                    b.HasKey("Email", "Host");

                    b.ToTable("FaucetUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
